manifest:
  defaults:
    remote: cormoran
  remotes:
    - name: cormoran
      url-base: https://github.com/cormoran
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk-west-commands
      revision: v1.0.0
      import: true
    - name: zmk
      revision: main+dya
      import: app/west.yml
    - name: zmk-driver-pmw3610-with-custom-studio-rpc
      revision: main
  self:
    path: config
