name: Build ZMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        continue-on-error: true
        env:
          cache_name: cache-west-modules
        with:
          path: |
            zmk/
            zephyr/
            modules/
            zmk-west-commands/
            zmk-driver-pmw3610-with-custom-studio-rpc/
          key: ${{ runner.os }}-build-${{ env.cache_name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache_name }}-

      - name: Init
        run: |
          git config --global --add safe.directory '*'
          west init -l config
          west update --narrow
          west zephyr-export

      - name: Build
        run: |
          west zmk-build -d ./build \
            --extra-module-auto-discovery zmk-config \
            -m "${PWD}/zmk-driver-pmw3610-with-custom-studio-rpc"

      - name: Copy artifacts
        shell: sh -x {0}
        run: |
          mkdir -p artifacts
          find ./build -type f -path '*/zephyr/zmk.uf2' \
          | while read -r f; do
              echo "Found: $f"
              name=$(basename "$(dirname "$(dirname "$f")")")
              mv "$f" "artifacts/${name}.uf2"
            done

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cool642tb-mini
          path: artifacts
